version: '3'
services:
  db:
    image: mysql:5.7
    container_name: sql_lab_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnerable
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  app:
    image: vulnerables/web-dvwa
    container_name: sql_lab_app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: vulnerable
    ports:
      - "8080:80"
    depends_on:
      - db
